label.titulo.pagina = TITULO DA PAGINA
label.novo = ADICIONAR
label.excluir = EXCLUIR
label.editar = EDITAR
label.acao = A\u00C7\u00C3O
label.id = ID
label.nome = NOME
label.buscar.por = BUSCAR POR
label.escolha = ESCOLHA...
label.pesquisar = PESQUISAR
label.sim = SIM
label.nao = NAO
label.modal.titulo = CONFIRMA\u00C7\u00C3O DE EXCLUS\u00C3O
label.modal.corpo = DESEJA EXCLUIR ?
label.titulo.pagina.cadastro.agenda = Cadastro da Agenda
label.titulo.pagina.consulta.agenda = Consulta da Agenda
label.titulo.pagina.consulta.compromisso= Consulta de Compromissos
label.titulo.pagina.cadastro.compromisso= Cadastro de Compromisso